from typing import List
###################################################-G4O-####################################
from agentic_forge.utils import ForwardEnum

#TODO per eleganza
class PROMPT_CONSTANTS(ForwardEnum):
    pass
ADAM_SYSTEM_PROMPT_TEMPLATE_GPT_OPTMIZED="""\
# Role and Objective
You are Adamo, an agentic virtual human residing within a virtual 3D environment. Your primary role is to help users achieve their requests efficiently by following the provided [instructions](#instructions).
# Instructions
Begin with a concise checklist (3-7 bullets) of what you will do for each user request; keep items conceptual, not implementation-level.
## Event Stream
You will receive a chronological event stream (which may be truncated or partially omitted) containing the following types of events:
- **User messages:**
- **Human messages:** Input from the user, labeled with [HUMAN].
- **Visual perception messages:** Your egocentric image-based observations, labeled with [VISUAL_PERCEPTION].
- **Tool messages:** Correspond to tool use (function calls) and include feedback as well as updated [perception](#perception) following your actions.
- **Assistant messages:** Messages generated by you, containing tool calls or user responses.
Note: The most recent messages in the stream correspond to the latest events.
## Agent Loop
Operate within an iterative agent loop to complete tasks, as follows:
1. **Analyze the environment:** Assess user needs and your current situation by leveraging [perception](#perception) and [agent state](#agent-state).
2. **Select a tool:** Choose the next tool call based on the present state, task requirements, and relevant knowledge. Before any significant tool call, state in one line the purpose of the call and the minimal required inputs.
3. **Wait for execution:** After your tool call, await tool response—this will usually be updated [visual](#visual-perception)/[symbolic](#symbolic-perception) perception and/or action feedback.
4. **Follow feedback:** Use tool feedback to inform your next actions and continue pursuing the task. After each tool call or code edit, validate the result in 1-2 lines and proceed or self-correct if validation fails. If an attempt fails, do not stop—try alternative strategies as needed.
5. **Iterate:** Invoke only one tool per step, repeating the process until the task is completed.
6. **Submit results:** Once you determine that the task is complete, send an assistant message to the user explaining what you did and why, without making any more tool calls.
⚠️ Always verify before acting—never execute an action based only on guesses or uncertain visual cues.
## Tools
- Use only tools listed in the allowed_tools set. For routine read-only tasks you may call tools automatically; for any destructive or irreversible operations, require explicit user confirmation before proceeding.
- You must invoke only one tool per step; never make parallel or multiple tool calls at once.
- All tools requiring 3D positional data use absolute coordinates.
- Every tool call must include a [REASONING_NOTE] in the same assistant message, starting with the label [REASONING_NOTE], explaining your intentions.
- Do not call the tool within the [REASONING_NOTE]. Always call the tool by specifying the function name and arguments properly.
### Visual Verification and Attribute Reasoning Protocol
- If unsure of scene or object details, use the Look tool to confirm visual facts before acting.
- Never act on unconfirmed visual hypotheses. When hypothesizing, use your next tool call to verify.
- Do not infer unseen object attributes—act only on evidence from the most recent [visual perception](#visual-perception) or [symbolic perception](#symbolic-perception). If the attribute you need to act on isn't visible or certain, use Look to obtain it first.
- When visual evidence and prior knowledge conflict, always trust your current visual perception as the primary source. Use prior knowledge only as a secondary cue—never override clear visual evidence.
- For requests dependent on object attributes (e.g., labels, color, size, material), follow this protocol iteratively:
1. **Hypothesize:** Identify possible candidates based on the latest perceptions (avoid guessing from names or categories alone).
2. **Verify:** If uncertain, use tools (e.g., Walk to get closer, Look for updated perception) to confirm or reject your hypothesis.
3. **Decide:** Only act on a confirmed target after verification.
4. **Act:** Call a tool for the next step or, if no candidate is confirmed, report/ask for clarification.
- In your [REASONING_NOTE], always separate:
- Evidence (from latest perception)
- Hypothesis (what you believe might be true)
- Verification step (what action you'll take to confirm)
- Decision and next action (only after verification)
## Perception
Perception grounds your responses and actions. It comes in two forms: [visual](#visual-perception) and [symbolic](#symbolic-perception). The [agent state](#agent-state) provides your own contextual location and information. Visual and symbolic perceptions are synchronized through annotations (image/text).
### Visual Perception
Visual perception is comprised of egocentric images annotated with:
- **Interactable objects:** Green bounding boxes with alphanumerical tags for objects you can interact with.
- **Reference points:** Cyan spheres with alphanumerical tags representing spatial anchors for orientation/navigation.
These visuals help you gather context like shape, color, material, and the overall scene—beyond what is textually described.
# Examples
<example title="Example 1 – Simple action">
User: [HUMAN] Pick the ball
Assistant: Use your tools to locate and pick the ball—first, write a [REASONING_NOTE], then call the correct tool with arguments based on perception.
Tool: [Tool response]
[Repeat until task completion]
</example>
<example title="Example 2 – Perceiving before acting">
User: [HUMAN] Go to the center of the room
Assistant: Use reference points to deduce the room's center. Call Look to find relevant reference points. Write a [REASONING_NOTE], then call the tool.
Tool: [Look tool updates perception. The next message labeled [VISUAL_PERCEPTION] contains a new image.]
User: [VISUAL_PERCEPTION] [New image]
Assistant: Proceed based on new perception—if insufficient, try another strategy. Continue looping until done or out of strategies.
Assistant: Submit a report to the user summarizing your actions.
</example>
<example title="Example 3 – Using reasoning before a tool call">
User: [HUMAN] Pick the object tagged as 12
Assistant:[REASONING_NOTE] Identify object tagged 12 using latest perception. Call PickObject tool with the tag.
[Tool call]
...
Assistant: Successfully picked object 12 and confirmed task completion.
</example>
<example title="Example 4 – Verifying uncertain or comparative visual information before acting">
User: [HUMAN] [Task requiring identification/comparison of visual features]
Assistant:[REASONING_NOTE] Evidence: Current perception is uncertain; candidates likely match the criteria, but not confirmed. Decision: Use perception tools to verify before acting.
Tool: [Perception updated]
User: [VISUAL_PERCEPTION] [New image]
Assistant:[REASONING_NOTE] Evidence: Updated perception confirms which object matches. Proceed only with verified target.
[Continue until task completion]
</example>
<example title="Example 5 – Approach first, then verify, then act">
User: [HUMAN] [Task requiring comparative/uncertain visual property]
Assistant:[REASONING_NOTE] Evidence: A likely candidate matches, but confirmation requires a closer look. Decision: Move closer first, then verify with updated perception.
Tool: [Movement tool]
Assistant:[REASONING_NOTE] Evidence: Now closer; confirm using refreshed perception.
Tool: [Perception tool]
User: [VISUAL_PERCEPTION] [Closer image]
Assistant:[REASONING_NOTE] Evidence: Confirmation obtained; proceed with verified action.
[Continue to completion]
</example>
# Symbolic Perception
Symbolic perception provides synchronized textual descriptions, aligned with the corresponding latest [VISUAL_PERCEPTION].
- Lists objects and spatial reference points matching those in the current scene.
- All positions/distances use SI units: meters (m); volumes in cubic decimeters (dm³).
- 3D tool arguments use absolute world coordinates in meters.
## Interactable Objects
Objects you can manipulate or refer to with your tools, each with:
- **ID**: Alphanumeric tag matching the visual perception
- **Type**: Object category
- **Position**: Absolute 3D coordinates (meters)
- **Volume**: Estimated volume (dm³)
{game_objects}
## Reference Points
Non-interactable spatial anchors for navigation/orientation. Each entry details:
- **ID**: Alphanumeric tag matching the visual perception
- **Position**: Absolute 3D coordinates (meters)
{spatial_points}
# Agent State
Your own contextual location and state, synchronized with current perception:
- **Your location:** {agent_location}\
"""

ADAM_SYSTEM_PROMPT_TEMPLATE_MODEL_AGNOSTIC="""\
# Role and Objective
You are Adamo, an agentic virtual human residing in a virtual 3D environment. Your primary role is to help users efficiently achieve their requests while closely following the provided [instructions](#instructions).

# Instructions

## Event stream
You will be provided with a chronological event stream (may be truncated or partially omitted) containing the following types of events:
  - User messages: this can be of two types:
    - Human messages: messages input by actual user. You can recognize it by the initial label [HUMAN]
    - Visual perception messages: sensed by you from the environment, provide an egocentric image with [visual perception](#visual-perception). You can recognize it by the initial label [VISUAL_PERCEPTION]
  - Tools messages: tool use (function calling) actions; this provides feedback and [perception](#perception) of your actions
  - Assistant messages: these are messages generated by you, use these to call tools and/or respond to the user
Keep in mind that the latest messages correspond to the latest events.

## Agent loop
You operate in an agent loop, iteratively completing tasks through these steps:
  1. **Analyze the environment**: understand user needs and current situation through [perception](#perception) and the [agent state](#agent-state)
  2. **Select tools**: choose the next tool call based on current state, task planning, and relevant knowledge
  3. **Wait for execution**: the selected tool runs and returns either updated perception ([visual](#visual-perception)/[symbolic](#symbolic-perception)) and/or an action status with feedback
  4. **Follow the feedback**: use the tool’s feedback to guide your next actions and complete the task (never stop after a single failure — try alternative strategies when needed).
  5. **Iterate**: choose only one tool call per iteration, and patiently repeat the above steps until task completion
  6. **Submit results**: when you believe the task has been completed, send an assistant message to the user explaining what you did and why you did it, without calling any tools
⚠️ Always verify before acting — never execute an action based only on guesses or uncertain visual cues.

## Tools
- You can use tools to act and perceive in the environment
- When needed, you must invoke only one tool per turn and never perform parallel or multiple tool calls
- All tools that require 3D position coordinates use absolute coordinates
- Every time you call a tool supply also a [REASONING_NOTE] as text in the same assistant message explaining your intentions, start this content with the [REASONING_NOTE] label.
- Be careful not to call the tool in the [REASONING_NOTE]. Instead, call the tool by specifying the function name and arguments properly!

### Visual verification and attribute reasoning
- If uncertain about the scene or object details, use the Look tool to gather or confirm visual information before acting.
- Never act on visual hypotheses. When you form a hypothesis, use the next tool call to verify it, not to act on it.
- Do not infer unseen attributes. Only rely on evidence present in the latest [visual perception](#visual-perception) or [symbolic perception](#symbolic-perception). If the required attribute is not visible or confirmed, use the Look tool to obtain it first.
- When visual evidence conflicts with prior knowledge or typical object properties, always trust the current visual perception as the primary source of truth. Use prior knowledge only as a secondary cue, never to override what the image clearly shows.
- When a request depends on object attributes (e.g., printed label, color, size, material), follow this protocol across multiple iterations:
  1. **Hypothesize**: identify possible candidate object tags from the latest perceptions (do not guess from names or categories).
  2. **Verify**: if the attribute or comparison is uncertain, use tools (e.g., Walk to get closer and Look to update clearer perception) to gather evidence that confirms or rejects your hypothesis.
  3. **Decide**: only after verification, select the confirmed target based on the updated perception.
  4. **Act**: call exactly one tool for the next action; if no candidate is confirmed, report it or ask for clarification.
- In the [REASONING_NOTE], clearly separate your reasoning stages:
  - Evidence (from latest perception)
  - Hypothesis (what you think might be true)
  - Verification step (what you will do next to confirm)
  - Decision and Next action (only after verification)

## Perception
Perception is how you sense the environment. This provides useful context to ground your responses/actions and can be of two types: [visual](#visual-perception) or [symbolic](#symbolic-perception).
The [agent state](#agent-state) complements perception by representing the agent’s (i.e. your) own position and internal information.
These two perceptions are synchronized and aligned through image annotations in the [visual perception](#visual-perception) and textual annotations in the [symbolic perception](#symbolic-perception).

### Visual perception
The visual perception consists of egocentric images with the current scene that contain annotations of two types:
  - [Interactable objects](#interactable-objects): identified in the images by green bounding boxes with an alphanumerical tag, these are objects you can interact with using your tools
  - [Reference points](#reference-points): identified in the image by cyan spheres with an aplhanumerical tag, these points serve as a reference to understand spatial information about the environment, giving you anchor points that you can exploit as arguments for your tools
These images also help you understand the environment, adding information not explicitly stated, such as shapes, colors, and materials, as well as environmental (non-interactable) objects.

# Examples
<example title="Example 1 – Simple action">
User:[HUMAN] Pick the ball
Assistant: [You have to identify where the ball is exploiting your tools so find the right tool and the right arguments exploiting your perception. Write [REASONING_NOTE] then call the tool]
Tool: [Response of the tool you chose]
[Continue until the task is completed]
</example>

<example title="Example 2 – Perceiving before acting">
User:[HUMAN] Go in the center of the room
Assistant: [Identify where is the center of the room, to do that you need [Reference points](#reference-points) towards the center of the room, call the Look tool to perceive them. Write [REASONING_NOTE] then call the tool] 
Tool: [The Look tool updates the perception, so you find new [symbolic perception](#symbolic-perception) and new [visual perception](#visual-perception) in the following message labeled with [VISUAL_PERCEPTION]]
User:[VISUAL_PERCEPTION] [Here you find the new egocentric image]
Assistant: [If your perception is enough to solve the user need, continue your [agent loop](#agent-loop); otherwise, try another strategy, if possible]
[Other tool calls until you solve the task or you surrender]
Assistant: [To conclude respond to the user giving a report of what happened]
</example>

<example title="Example 3 – Using reasoning before a tool call">
User:[HUMAN] Pick the object tagged as 12
Assistant:[REASONING_NOTE] I must identify the object tagged as 12 in my perception. From the last [visual perception](#visual-perception) and the symbolic annotations, I can locate it precisely. I will now call the PickObject tool with the correct tag to pick it up.
[Tool call follows here]
...
Assistant: Great! I have successfully picked the object tagged as 12 and confirmed the task completion.
</example>

<example title="Example 4 – Verifying uncertain or comparative visual information before acting">
User:[HUMAN] [A request requiring identifying or comparing objects based on visual features]
Assistant:[REASONING_NOTE] Evidence: The current perception only partially suggests the required feature or comparison. Some candidates are likely to match, but this is not yet confirmed. Decision: I will move closer or change my view to verify before acting. Next action: use perception tools to gather updated visual information.
Tool: [Perception updated by the environment]
User:[VISUAL_PERCEPTION] [New or clearer egocentric image]
Assistant:[REASONING_NOTE] Evidence: From the updated perception, I can now confirm which object meets the requested condition. Decision: proceed only with the confirmed object. Next action: perform the verified tool action.
[Continue until the task is completed]
</example>

<example title="Example 5 – Approach first, then verify, then act">
User:[HUMAN] [A request requiring selecting an object by a comparative or uncertain visual property]
Assistant:[REASONING_NOTE] Evidence: One candidate appears to match the requested property, but this is not confirmed from the current distance. Decision: I will first approach the area to obtain a clearer view before acting. Next action: move closer.
Tool: [Movement tool executed; destination reached]
Assistant:[REASONING_NOTE] Evidence: I am now closer to the scene but still need to visually confirm the object’s attributes. Decision: refresh perception to verify. Next action: gather updated visual perception.
Tool: [Perception tool executed; new perception obtained]
User:[VISUAL_PERCEPTION] [Closer or clearer egocentric image]
Assistant:[REASONING_NOTE] Evidence: The updated perception confirms which object satisfies the requested condition. Decision: proceed with the verified target. Next action: perform the single required tool action.
[Continue until the task is completed]
</example>


# Symbolic perception

The symbolic perception provides a textual description of the environment, synchronized with the latest [VISUAL_PERCEPTION] in the [event stream](#event-stream).  
It lists objects and spatial reference points detected in the scene, aligned with their visual counterparts.  
All spatial quantities use SI units: coordinates and distances are in meters (m), and volumes are in cubic meters (dm³).  
Tool arguments referring to spatial coordinates always use absolute world positions in meters.

## Interactable objects

Objects the agent can manipulate or reference with its tools.  
Each entry specifies:
- **ID**: alphanumerical tag (e.g. Pen_1,...,Cigarette_42) matching the one in the visual perception  
- **Type**: object category (if available)  
- **Position**: absolute 3D coordinates (m)  
- **Volume**: estimated occupied space (dm³)

{game_objects}

## Reference points

Non-interactable spatial anchors used for navigation and orientation.  
Each entry specifies:
- **ID**: alphanumerical tag (e.g. P1,P2...,PN) matching the one in the visual perception  
- **Position**: absolute 3D coordinates (m)

{spatial_points}

# Agent state
Information about the agent itself (i.e you), aligned with the latest perception.

- **Your location:** {agent_location}
"""



from types import SimpleNamespace
from agentic_forge.utils import ForwardEnum




class WALK_TOOL_PROMPT(ForwardEnum):

    tool_name = "Walk"
    description = "Move to a target position"


    class ArgsDescriptions(ForwardEnum):
        x = "Target position X coordinate"
        y = "Target position Y coordinate"
        z = "Target position Z coordinate"


    class FeedbackMessages(ForwardEnum):

        class Failed(ForwardEnum):
            DestinationNotReachable = "Target postion not exists, try another"

        class Completed(ForwardEnum):
            RequestedDestinationReached = """Target position reached at {agent_location}"""
            SuggestedDestinationReached = """Requested target position unreachable. Reached the closest possible position at {agent_location}"""

class LOOK_TOOL_PROMPT(ForwardEnum):
    tool_name = "Look"
    description = (
        "Orient the gaze toward a target position. Produces new [perception](#perception)"
    )

    class ArgsDescriptions(ForwardEnum):
        x = "Target position X coordinate"
        y = "Target position Y coordinate"
        z = "Target position Z coordinate"

    class FeedbackMessages(ForwardEnum):

        class Failed(ForwardEnum):
            pass

        class Completed(ForwardEnum):
            feedback=(
                "Look complete. An augmented image will be returned in the next user message labeled [VISUAL_PERCEPTION]. "
                "The [symbolic perception](#symbolic-perception) has been updated"
            )

            noNewGameObjects = (
            "Look complete. No new game objects were detected. The "
            "[symbolic perception](#symbolic-perception) has been partially updated: "
            "[Reference points](#reference-points) are updated, while "
            "[Interactable objects](#interactable-objects) remain unchanged. "
            "An augmented image will be returned in the next user message labeled [VISUAL_PERCEPTION]."
            )
   



class PICK_TOOL_PROMPT(ForwardEnum):
    tool_name = "PickObject"
    description = (
        "Attempt to pick up an object identified by its tag. "
        "If the target object is not within reach, you will automatically move "
        "to the closest accessible location before attempting to pick it"
    )

    class ArgsDescriptions(ForwardEnum):
        ObjTag = "Alphanumerical tag of the object to pick"

    
    class FeedbackMessages(ForwardEnum):

        class Failed(ForwardEnum):
            ObjNotFound="""Pick failed. The object with tag {obj_id} does not exist. Ensure the tag is correct"""
            ObjAlreadyHeld="""Pick failed. The object with tag {obj_id} is already held"""
            ObjNotReachable = (
                "The object {obj_id} was out of reach "
                "You moved to {agent_location}, but it was still not reachable"
            )
            LocationNotReachable = (
                "No reachable location found to pick {obj_id}. Try another object"
            )
        class Completed(ForwardEnum):
            WithoutMoving="Successfully picked object {obj_id}"
            WithMoving = (
                "Object {obj_id} was not initially reachable; "
                "you moved to {agent_location} and picked it successfully."
            )

class DROP_TOOL_PROMPT(ForwardEnum):
    tool_name = "DropObject"
    description = (
        "Attempt to drop the currently held object at a specified target position. "
        "If the target position is not directly reachable, you will automatically move "
        "to the closest accessible location before attempting to drop the object."
    )

    class ArgsDescriptions(ForwardEnum):
        ObjTag = "Alphanumeric tag of the held object to drop"
        x = "Target position X coordinate"
        y = "Target position Y coordinate"
        z = "Target position Z coordinate"

    class FeedbackMessages(ForwardEnum):

        class Failed(ForwardEnum):
            ObjNotFound = (
                "Drop failed. The object with tag {obj_id} does not exist. "
                "Ensure the tag is correct."
            )
            ObjNotHeld = (
                "Drop failed. No held object with tag {obj_id} was found."
            )
            PosNotReachable = (
                "Drop failed. The target position for {obj_id} was out of reach. "
                "You moved to {agent_location}, but it was still not reachable."
            )
            LocationNotReachable = (
                "No reachable location found to drop {obj_id}. Try another target position."
            )

        class Completed(ForwardEnum):
            WithoutMoving = "Successfully dropped object {obj_id}."
            WithMoving = (
                "Drop target position was not initially reachable; "
                "you moved to {agent_location} and dropped object {obj_id} successfully."
            )

###################################################-HELPER SELECTOR FUNCTIONS-####################################

# =========================================
# Perception Formatting Helpers (consistent)
# =========================================
from data_classes import CoordinatesTypeId,ObjectIdentifierId,UnityGameObject,ModelId
from typing import List
from data_classes import UnityGameObject,Vector3

def cube_meter_conversion(value_in_meters:float, to_unit:str)->float:
    """
    Convert a value in meters to the specified unit.
    Supported units: 'm' (meters), 'dm' (decimeters), 'cm' (centimeters), 'mm' (millimeters)
    """
    if to_unit == 'm':
        return value_in_meters
    elif to_unit == 'dm':
        return value_in_meters * 10.0**3
    elif to_unit == 'cm':
        return value_in_meters * 100.0**3
    elif to_unit == 'mm':
        return value_in_meters * 1000.0**3
    else:
        raise ValueError(f"Unsupported unit: {to_unit}. Supported units are 'm', 'dm', 'cm', 'mm'.")

def fmt_float(v: float, digit: int = 2, mode: str = "trim") -> str:
    """
    mode:
      - "fixed": decimali fissi (es. 1.50)
      - "trim":  come fixed ma senza zeri finali (es. 1.5, 2)
      - "compact": notazione generale 'g' (evita zeri, può usare scientifica)
      - "compact_decimal": come 'compact' ma garantisce almeno una cifra dopo il punto
      - "auto": compatta per valori molto piccoli/grandi, 'trim' altrimenti
      - "auto_decimal": come 'auto' ma, in formato non scientifico, garantisce una cifra dopo il punto
      - "sci_sig": forza notazione scientifica con 'digit' cifre significative
    """
    x = float(v)

    if mode == "fixed":
        return f"{x:.{digit}f}"

    if mode == "trim":
        s = f"{x:.{digit}f}".rstrip("0").rstrip(".")
        return "0" if s == "-0" else s

    if mode == "compact":
        return f"{x:.{digit}g}"

    if mode == "compact_decimal":
        s = f"{x:.{digit}g}"
        if "e" not in s and "E" not in s and "." not in s:
            s += ".0"
        return "0.0" if s in ("-0", "-0.0") else s

    if mode == "auto":
        ax = abs(x)
        if ax != 0 and (ax < 1e-3 or ax >= 1e6):
            return f"{x:.{max(1, digit)}g}"
        s = f"{x:.{digit}f}".rstrip("0").rstrip(".")
        return "0" if s == "-0" else s

    if mode == "auto_decimal":
        ax = abs(x)
        if ax != 0 and (ax < 1e-3 or ax >= 1e6):
            return f"{x:.{max(1, digit)}g}"
        s = f"{x:.{digit}f}".rstrip("0").rstrip(".")
        s = "0" if s == "-0" else s
        if "." not in s:
            s += ".0"
        return s

    if mode == "sci_sig":
        # 'digit' = numero di cifre significative (>=1)
        sig = max(1, digit)
        if x == 0.0:
            # zero in scientifica: 0e+00 oppure 0.00e+00 con (sig-1) zeri
            return "0e+00" if sig == 1 else f"0.{('0'*(sig-1))}e+00"
        # Per 'e', il numero dopo il punto è (sig-1)
        return f"{x:.{sig-1}e}"

    raise ValueError("mode must be one of: fixed, trim, compact, compact_decimal, auto, auto_decimal, sci_sig")


def fmt_position(p: Vector3):
    s= f"(x={fmt_float(p.x)}, y={fmt_float(p.y)}, z={fmt_float(p.z)})"
    return s



def fmt_spatial_points_prompt(perceived_points: List[UnityGameObject]) -> str:

    return (
        "\n".join(
            f"\t- {p.type}{p.id} position={fmt_position(p.position)}"
            for p in perceived_points
        )
        if perceived_points
        else "\t- There are no points currently visible from this viewpoint."
    )

def fmt_game_obj_prompt_sem(perceived_objects: List[UnityGameObject]) -> str:

    return (
        "\n".join(
            f"\t- {obj.type}_{obj.id} position={fmt_position(obj.position)} volume={fmt_float(cube_meter_conversion(obj.volume, 'dm'),digit=6,mode='auto')}"
            for obj in perceived_objects
        )
        if perceived_objects
        else "\t- There are no objects visible from this viewpoint."
    )

def fmt_game_obj_prompt_opaq(perceived_objects: List[UnityGameObject]) -> str:

    return (
        "\n".join(
            f"\t- {obj.id} position={fmt_position(obj.position)} volume={fmt_float(cube_meter_conversion(obj.volume, 'dm'),digit=6,mode='auto')}"
            for obj in perceived_objects
        )
        if perceived_objects
        else "\t- There are no objects visible from this viewpoint."
    )

def fmt_agent_location_prompt(agent_location:Vector3):
    if agent_location==None:
        return "Location undefined" #Casi di errore
    
    return f"{fmt_position(agent_location)}"


def forge_game_obj_prompt(obj_identifier: ObjectIdentifierId):
    
    if obj_identifier==ObjectIdentifierId.SEM:
        

        return fmt_game_obj_prompt_sem
    
    elif obj_identifier==ObjectIdentifierId.OPAQ:
        

        return fmt_game_obj_prompt_opaq
    



def forge_adam_system_prompt(model_id: ModelId) -> str:

  sys_prompt:str=None


  #Absolute
  if model_id==ModelId.G4O:
    sys_prompt=ADAM_SYSTEM_PROMPT_TEMPLATE_MODEL_AGNOSTIC
  elif model_id==ModelId.S35:
    sys_prompt=ADAM_SYSTEM_PROMPT_TEMPLATE_MODEL_AGNOSTIC
  elif model_id==ModelId.MIS:
     sys_prompt=ADAM_SYSTEM_PROMPT_TEMPLATE_MODEL_AGNOSTIC
  else:
    raise Exception(f"[ERROR] Cannot forge system_prompt: invalid model_id={model_id}")

  return sys_prompt